"""empty message

Revision ID: 09a2e2846b4f
Revises: 39b15c49cf7c
Create Date: 2025-03-15 17:13:59.023641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a2e2846b4f'
down_revision = '39b15c49cf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
