"""empty message

Revision ID: 1e2d7451fb2b
Revises: 7b6f09fe4ca0
Create Date: 2025-03-04 13:48:33.979393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2d7451fb2b'
down_revision = '7b6f09fe4ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoteles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint('estudiantes_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.create_unique_constraint('estudiantes_nombre_key', ['nombre'])

    op.drop_table('hoteles')
    # ### end Alembic commands ###
