"""empty message

Revision ID: 397ee445725f
Revises: 6e3dca654b5b
Create Date: 2025-03-11 19:10:38.408252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397ee445725f'
down_revision = '6e3dca654b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoteles', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoteles', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
