"""empty message

Revision ID: 39b15c49cf7c
Revises: a828c9d11015
Create Date: 2025-03-15 16:47:24.288551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b15c49cf7c'
down_revision = 'a828c9d11015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=120), nullable=True))
        batch_op.drop_column('condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
