"""empty message

Revision ID: 45e78a44ebe1
Revises: 8a0b24a5ab3e
Create Date: 2025-03-15 12:04:00.457563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e78a44ebe1'
down_revision = '8a0b24a5ab3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.drop_constraint('housekeepertask_photo_key', type_='unique')
        batch_op.drop_column('condition')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('housekeepertask_photo_key', ['photo'])

    # ### end Alembic commands ###
