"""empty message

Revision ID: 51695fd7e4b3
Revises: 921e52b39dda
Create Date: 2025-03-18 07:31:39.335794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51695fd7e4b3'
down_revision = '921e52b39dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=80), nullable=False))
        batch_op.drop_column('status')

    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=120), nullable=True))
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('maintenance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('housekeeper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('housekeeper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('maintenance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('condition')

    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
