"""empty message

Revision ID: 8a0b24a5ab3e
Revises: 41a739eb3acb
Create Date: 2025-03-15 11:50:26.855455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0b24a5ab3e'
down_revision = '41a739eb3acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint('housekeepertask_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.create_unique_constraint('housekeepertask_nombre_key', ['nombre'])
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
