"""empty message

Revision ID: a828c9d11015
Revises: 45e78a44ebe1
Create Date: 2025-03-15 16:28:26.516321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a828c9d11015'
down_revision = '45e78a44ebe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.alter_column('housekeeper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('maintenancetask_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.create_unique_constraint('maintenancetask_nombre_key', ['nombre'])
        batch_op.alter_column('housekeeper_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
