"""empty message

Revision ID: b60b1e0b9830
Revises: 7ad41d8b2349
Create Date: 2025-03-15 10:51:52.690659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60b1e0b9830'
down_revision = '7ad41d8b2349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('room_branch_id_fkey', type_='foreignkey')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('room_branch_id_fkey', 'branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###
