"""empty message

Revision ID: b63af2d1d23d
Revises: ddf80001ee1d
Create Date: 2025-03-18 21:42:17.230379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63af2d1d23d'
down_revision = 'ddf80001ee1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeeper', schema=None) as batch_op:
        batch_op.drop_column('foto_url')

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('housekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
