"""empty message

Revision ID: ddf80001ee1d
Revises: d26a749e6f73
Create Date: 2025-03-18 19:12:01.176418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf80001ee1d'
down_revision = 'd26a749e6f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.alter_column('hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###
